# Generated by Django 3.2.12 on 2022-02-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0007_dataset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Menge', max_digits=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', help_text='Kategorie', max_length=2),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='date_of_disposal',
            field=models.DateField(blank=True, help_text='Entsorgungsdatum', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='disposal_type',
            field=models.ForeignKey(blank=True, help_text='Entsorgungsart', null=True, on_delete=django.db.models.deletion.CASCADE, to='tnp.disposal_type'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='material',
            field=models.ForeignKey(help_text='Material', on_delete=django.db.models.deletion.CASCADE, to='tnp.material'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='point_of_origin',
            field=models.ForeignKey(help_text='Herkunftsort', on_delete=django.db.models.deletion.CASCADE, related_name='origin_address', to='tnp.address'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='recipient',
            field=models.ForeignKey(help_text='Empfänger', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_address', to='tnp.address'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sender',
            field=models.ForeignKey(help_text='Absender', on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='tnp.address'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='specie',
            field=models.ForeignKey(help_text='Tierart', on_delete=django.db.models.deletion.CASCADE, to='tnp.specie'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('o', 'open'), ('c', 'closed')], default='o', max_length=2),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='unit',
            field=models.ForeignKey(help_text='Einheit', on_delete=django.db.models.deletion.CASCADE, to='tnp.unit'),
        ),
    ]
