# Generated by Django 3.2.12 on 2022-03-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0009_rename_prospective_date_of_disposal_dataset_reminder_disposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Deutschland', help_text='Land', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='Stadt', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(help_text='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='PLZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='Straße', max_length=200),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='category',
            field=models.CharField(choices=[('1', '1 - high risk / hohes Risiko '), ('2', '2 - moderate risk / mittleres Risiko'), ('3', '3 - low risk / geringes Risiko')], default='3', help_text='Kategorie', max_length=2),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='point_of_origin',
            field=models.ForeignKey(help_text='Herstellungsort', on_delete=django.db.models.deletion.CASCADE, related_name='origin_address', to='tnp.address'),
        ),
    ]
